<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Cryptography.KeyDerivation" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit3TestAdapter" />
    <PackageReference Include="NUnit.Analyzers" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Bogus" />
    <PackageReference Include="FluentResults" />
    <PackageReference Include="FluentAssertions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\CloudSharp.Core\CloudSharp.Core.csproj" />
    <ProjectReference Include="..\TestSupport\CloudSharp.TestSupport.csproj" />
  </ItemGroup>

</Project>