<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi"/>
        <PackageReference Include="FluentResults"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\CloudSharp.Core\CloudSharp.Core.csproj" />
      <ProjectReference Include="..\CloudSharp.Infrastructure\CloudSharp.Infrastructure.csproj" />
    </ItemGroup>

</Project>
